-- Generated by convert_data_dump.py
-- Integer IDs -> UUIDs conversion

BEGIN;

-- Table: public.brands (3 rows)
INSERT INTO public."brands" ("id", "name", "slug", "logo", "description", "is_active", "created_at", "updated_at") VALUES
  ('ead39108-640a-4ad7-97c8-fbadbacc67d5', 'BumChums', 'bumchums', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/brand-logos/1789214724231-images.jpg', 'Leisurewear, activewear and Hoseiry', 't', '2026-09-12 12:06:04.293843+00', '2026-09-12 12:06:04.293843+00'),
  ('c3f535eb-1ab9-4b6d-bf8d-49e0ba89b9db', 'VIP', 'vip', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/brand-logos/1789214830374-download-(1).png', 'Innerwear and Hoseiry Clothing', 't', '2026-09-12 12:07:10.451787+00', '2026-09-12 12:07:10.451787+00'),
  ('886928e6-3908-4a0f-b59d-114e374f3c47', 'Frenchie', 'frenchie', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/brand-logos/1789235231200-Frenchie.webp', 'Hosiery Brief and long bottoms', 't', '2026-09-12 17:47:14.857171+00', '2026-09-12 17:47:14.857171+00')
ON CONFLICT DO NOTHING;

-- Table: public.categories (4 rows)
INSERT INTO public."categories" ("id", "name", "slug", "description", "is_active", "created_at", "updated_at", "image") VALUES
  ('fe79f9fa-f1b3-4512-b97a-ce9b3c887a93', 'Menswear', 'menswear', 'Mens clothing', 't', '2026-09-12 12:10:03.427337+00', '2026-09-12 12:19:27.375+00', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/categories/1789215567007-91d94b79-2002-484b-b141-09b7b629a616-Menswear.webp'),
  ('f6bffa9a-5dec-441a-9d9a-c0024d9f2928', 'Womenswear', 'womenswear', 'Innerwears and Hosiery', 't', '2026-09-12 13:29:35.735916+00', '2026-09-12 13:29:35.735916+00', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/categories/1789219775367-456a708b-f377-4f7c-9134-dfe94d46f976-Women.jpg'),
  ('ae66a6d3-993f-4d43-8efe-d6209401fe12', 'Kidswear', 'kidswear', 'Innerwear, Coordsets and much more', 't', '2026-09-12 13:30:30.274614+00', '2026-09-12 13:30:30.274614+00', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/categories/1789219829765-f2b65b5d-4788-4f9f-b034-3931d18a9e0b-Kidswear.jpg'),
  ('a16b50bf-9620-4b1b-81f6-0d4131279871', 'Atheletix', 'atheletix', 'Sports T-shirts, tracks and shorts', 't', '2026-09-12 13:31:23.305989+00', '2026-09-12 13:31:23.305989+00', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/categories/1789219882723-a353c83d-1ed3-4e73-b9c6-256bbfcaee8d-Athletix.webp')
ON CONFLICT DO NOTHING;

-- Table: public.colors (22 rows)
INSERT INTO public."colors" ("id", "name", "hex_code") VALUES
  ('dc1ea9b6-dd6b-4f90-a6ae-abfc8c4a254d', 'Black', '#000000'),
  ('9b20bce5-c5f2-4b78-8d37-3a48822054f8', 'White', '#FFFFFF'),
  ('5ab899d2-cacf-4aa3-b9cb-d144b094993e', 'Navy Blue', '#000080'),
  ('c7433f0d-0361-4009-9e37-5b8ecd9f1387', 'Royal Blue', '#4169E1'),
  ('2281c271-71c6-4aa4-bbe3-855457fcc515', 'Sky Blue', '#87CEEB'),
  ('107948df-b5a2-40b8-ad42-fe518caf5d31', 'Red', '#FF0000'),
  ('bc16ded3-e222-464b-a4b6-b927dfa55126', 'Maroon', '#800000'),
  ('f59e5a67-a232-483d-9583-e2dcf3bfbf4c', 'Pink', '#FFC0CB'),
  ('3923bbe6-07e9-4682-8e55-e8ab7d4452eb', 'Peach', '#FFDAB9'),
  ('3398b391-a448-4679-bfe5-4d3b729d80aa', 'Yellow', '#FFD700'),
  ('232edf7d-b4c5-47db-a2c9-a8ab7315d060', 'Mustard', '#FFDB58'),
  ('187b7899-85cc-4f74-8ef4-4d0eca8c1d19', 'Orange', '#FFA500'),
  ('579ed1cd-1979-49aa-8acd-76b3a3fef235', 'Green', '#008000'),
  ('67ce368a-6599-481a-a69c-6b79d4d00aa2', 'Olive Green', '#808000'),
  ('b267de8b-8b22-40d4-b2d9-db09f867f83c', 'Mint Green', '#98FF98'),
  ('38130b53-1159-4a34-98fe-64c42bdba0f6', 'Bottle Green', '#006A4E'),
  ('e94b3e98-c622-4660-b053-1a4664d010d9', 'Purple', '#800080'),
  ('b9e9d846-bbcb-4107-bc9d-27874349e061', 'Lavender', '#E6E6FA'),
  ('38c1fae0-e84e-4ebc-b3ba-47562f5d11a1', 'Grey', '#808080'),
  ('aff7b1f5-78b0-4e8e-96c5-e7e18f63428c', 'Beige', '#F5F5DC'),
  ('744e3784-6a1b-43d6-9684-6b03503f817d', 'Cinnamon', '#D2691E'),
  ('b9626bba-de79-48d5-bb92-b6cee94bf4ca', 'Onion Blue', '#6B7A8F')
ON CONFLICT DO NOTHING;

-- (no rows for public.coupons)

-- Table: public.sizes (8 rows)
INSERT INTO public."sizes" ("id", "name", "sort_order") VALUES
  ('052fdc07-55d9-4bd9-bcac-01d2899ff159', 'XS (75 cm / 30 inch)', '1'),
  ('e71e12ec-ad8c-44c8-8609-a3b18d5f886d', 'S (80 cm / 32 inch)', '2'),
  ('33a8081c-0512-41cf-8417-4438f78003e5', 'M (85 cm / 34 inch)', '3'),
  ('16ad71d8-226a-4bdd-8558-375f5a726360', 'L (90 cm / 36 inch)', '4'),
  ('0f9ee391-6bd5-4d6d-bb2e-3ff54c0a9e3c', 'XL (95 cm / 38 inch)', '5'),
  ('78db3b65-8787-418a-b053-44eac6d054a7', '2XL (100 cm / 40 inch)', '6'),
  ('93b4dd3d-4028-49ef-8fc5-fe712a3cf3c0', '3XL (105 cm / 42 inch)', '7'),
  ('dbd9ae31-2e47-4bc4-a336-41e9bf15a01c', '4XL (110 cm / 44 inch)', '8')
ON CONFLICT DO NOTHING;

-- Table: public.subcategories (3 rows)
INSERT INTO public."subcategories" ("id", "category_id", "name", "slug", "description", "is_active", "created_at", "updated_at", "image") VALUES
  ('52589ee7-8e48-4b1b-a6bd-afdbbf4608ae', 'fe79f9fa-f1b3-4512-b97a-ce9b3c887a93', 'T-shirts', 't-shirts', NULL, 't', '2026-09-12 13:48:19.235188+00', '2026-09-12 13:48:19.235188+00', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/subcategories/1789220898431-6230dfa7-700b-4c64-9920-0e15b14a85a1-menstshirt.webp'),
  ('c0f357e9-a16c-4f20-b6ec-c4cd395804bf', 'fe79f9fa-f1b3-4512-b97a-ce9b3c887a93', 'Track', 'track', NULL, 't', '2026-09-12 14:22:51.966762+00', '2026-09-12 14:22:51.966762+00', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/subcategories/1789222876422-c6438b80-fd89-4375-9de7-17aea5bd93ee-menstrack.jpg'),
  ('6f352152-cc9a-446b-a743-18828227995d', 'fe79f9fa-f1b3-4512-b97a-ce9b3c887a93', 'Underwear', 'underwear', NULL, 't', '2026-09-12 14:42:06.370145+00', '2026-09-12 14:42:06.370145+00', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/subcategories/1789224124659-97598594-307b-48a4-8796-5fe66894af69-VP-MI-TR-MAXER-2X5_3.webp')
ON CONFLICT DO NOTHING;

-- Table: public.products (4 rows)
INSERT INTO public."products" ("id", "category_id", "subcategory_id", "brand_id", "name", "gender", "slug", "model_no", "description", "sku", "is_active", "created_at", "updated_at") VALUES
  ('2461b38e-3fb5-4dff-ba38-72206440328d', 'fe79f9fa-f1b3-4512-b97a-ce9b3c887a93', '6f352152-cc9a-446b-a743-18828227995d', 'c3f535eb-1ab9-4b6d-bf8d-49e0ba89b9db', 'Ultima Solid Cotton Trunks for Men - Assorted Colours', 'Men', 'ultima-solid-cotton-trunks-for-men---assorted-colours', 'VP-MI-TR-ULTMC-10P', 'Introducing the VIP Ultima Trunks, made with 100% Combed Cotton fabric for ultimate softness and stretch-ability for an active lifestyle. Featuring a mid-rise fit and a soft outer elasticized waistband that leaves no marks, these trunks offer better durability and comfort. Upgrade your underwear game today!', 'AE-001', 't', '2026-09-12 16:56:49.271798+00', '2026-09-12 16:56:49.271798+00'),
  ('3a9c9ee7-2910-49d2-853a-82f419c61ae6', 'fe79f9fa-f1b3-4512-b97a-ce9b3c887a93', '6f352152-cc9a-446b-a743-18828227995d', 'c3f535eb-1ab9-4b6d-bf8d-49e0ba89b9db', 'Unique   Men''s   Snug   Fit   100%   Cotton   Trunks   -   Assorted   Colours', 'Men', 'unique-mens-snug-fit-100-cotton-trunks---assorted-colours', 'VP-MI-TR-UNICL-10P', 'Discover the ultimate comfort with our VIP Unique Trunks. Made with 100% combed cotton jersey fabric, these trunks feel incredibly soft on your skin. The stretchable mid rise design and contoured double pouch provide a snug fit for better durability. Plus, the tag-free and soft concealed waistband ensures no marks, making them perfect for everyday wear.', 'AE-002', 't', '2026-09-12 17:32:57.877507+00', '2026-09-12 17:32:57.877507+00'),
  ('a4056700-524f-4e88-bbe2-b2ba08db7e5d', 'fe79f9fa-f1b3-4512-b97a-ce9b3c887a93', '6f352152-cc9a-446b-a743-18828227995d', '886928e6-3908-4a0f-b59d-114e374f3c47', 'Plus   Color   Men   100%   Combed   Cotton   Brief   -   Assorted   Color', 'Men', 'plus-color-men-100-combed-cotton-brief---assorted-color', 'FR-MI-BF-PLUSC-10P', 'Experience the difference of 100% combed cotton, smoother than regular cotton, for exceptional comfort against your skin.
Stay fresh and dry with superior absorbency and breathable cotton fabric.
Say goodbye to pinching! The concealed waistband ensures a smooth, comfortable fit throughout the day.
Contoured leg openings and full back coverage provide extra comfort without restricting movement.
The FRENCHIE Plus Men''s Brief is the perfect choice for all-day wear, keeping you feeling comfortable and confident, no matter the activity..', 'AE-003', 't', '2026-09-12 17:52:01.932528+00', '2026-09-12 17:52:01.932528+00'),
  ('36ffc468-746a-44dd-b7d9-9139356c9b5b', 'fe79f9fa-f1b3-4512-b97a-ce9b3c887a93', '52589ee7-8e48-4b1b-a6bd-afdbbf4608ae', 'c3f535eb-1ab9-4b6d-bf8d-49e0ba89b9db', 'Men''s   Solid   White   004   Leisurewear   Essential   Cotton   Tee', 'Men', 'mens-solid-white-004-leisurewear-essential-cotton-tee', NULL, 'Made from 100% cotton jersey, soft and comfortable, keeps you cool.
Ribbed round neck, standard fit, and half sleeves for a casual wear.
Textured logo in hem line adds a stylish touch.
Pair with jeans and shoes to complete the look.
Stay cool and dry in this Rivolta Men''s wardrobe essential.', 'AE-003', 't', '2026-09-12 18:09:13.167477+00', '2026-09-13 09:00:38.538+00')
ON CONFLICT DO NOTHING;

-- Table: public.product_sizes (20 rows)
INSERT INTO public."product_sizes" ("id", "product_id", "size_id", "price", "mrp", "sku", "is_active") VALUES
  ('9a432c38-3771-44aa-bb6a-1c4b10aa34f2', '2461b38e-3fb5-4dff-ba38-72206440328d', 'e71e12ec-ad8c-44c8-8609-a3b18d5f886d', '165.00', '165.00', NULL, 't'),
  ('3bfb7dd6-ca58-4e37-928b-687419461b58', '2461b38e-3fb5-4dff-ba38-72206440328d', '33a8081c-0512-41cf-8417-4438f78003e5', '165.00', '165.00', NULL, 't'),
  ('df51a9ca-b0e6-42d7-ad36-06063aba1380', '2461b38e-3fb5-4dff-ba38-72206440328d', '16ad71d8-226a-4bdd-8558-375f5a726360', '165.00', '165.00', NULL, 't'),
  ('9b8c33ab-17d7-400c-bd81-fe5ab531f619', '2461b38e-3fb5-4dff-ba38-72206440328d', '0f9ee391-6bd5-4d6d-bb2e-3ff54c0a9e3c', '191.00', '191.00', NULL, 't'),
  ('c1420e62-bdf0-4d52-8a50-4895dfc520e9', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', 'e71e12ec-ad8c-44c8-8609-a3b18d5f886d', '160.00', '160.00', NULL, 't'),
  ('9d3de1f1-a9ba-4dbf-9d19-c806c1135c17', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', '33a8081c-0512-41cf-8417-4438f78003e5', '160.00', '160.00', NULL, 't'),
  ('136f3a11-7382-481e-943b-559f44fdf863', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', '16ad71d8-226a-4bdd-8558-375f5a726360', '150.00', '150.00', NULL, 't'),
  ('75119ada-8eaf-48ce-96ec-6f3952cb2e5f', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', '0f9ee391-6bd5-4d6d-bb2e-3ff54c0a9e3c', '166.00', '166.00', NULL, 't'),
  ('e147ae5a-6a02-4857-9c44-1a049cb83797', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', '78db3b65-8787-418a-b053-44eac6d054a7', '166.00', '166.00', NULL, 't'),
  ('568f1efe-b209-44ae-ab3e-4ee1de2f9152', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', 'dbd9ae31-2e47-4bc4-a336-41e9bf15a01c', '189.00', '189.00', NULL, 't'),
  ('ab88fc21-a4b5-496a-bba7-b6e8266fad08', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', 'e71e12ec-ad8c-44c8-8609-a3b18d5f886d', '122.00', '122.00', NULL, 't'),
  ('5a490137-f048-4ed6-ba75-a68bf9e314ef', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', '33a8081c-0512-41cf-8417-4438f78003e5', '135.00', '135.00', NULL, 't'),
  ('fe8d106f-32ff-4ffb-b077-90c0e4fd6f84', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', '16ad71d8-226a-4bdd-8558-375f5a726360', '135.00', '135.00', NULL, 't'),
  ('2b937abe-f06b-4ca7-bf8b-c6257eb5971f', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', '0f9ee391-6bd5-4d6d-bb2e-3ff54c0a9e3c', '135.00', '135.00', NULL, 't'),
  ('46730c4f-90ad-4772-82e7-4851db99b5af', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', '78db3b65-8787-418a-b053-44eac6d054a7', '135.00', '135.00', NULL, 't'),
  ('44b32192-256f-48c5-aa09-0ec9aa2c2cbc', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', 'dbd9ae31-2e47-4bc4-a336-41e9bf15a01c', '135.00', '135.00', NULL, 't'),
  ('87cd4dab-dabc-4802-a92e-ccbe3daa8bd3', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '33a8081c-0512-41cf-8417-4438f78003e5', '399.00', '399.00', NULL, 't'),
  ('08954035-99fa-4258-b28d-67ff2c54969e', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '16ad71d8-226a-4bdd-8558-375f5a726360', '399.00', '399.00', NULL, 't'),
  ('6b0d1136-3951-4898-b356-1ec8642a6176', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '0f9ee391-6bd5-4d6d-bb2e-3ff54c0a9e3c', '399.00', '399.00', NULL, 't'),
  ('cd1e67e4-e7f9-4fdc-af60-eb9798cfe04c', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '78db3b65-8787-418a-b053-44eac6d054a7', '399.00', '399.00', NULL, 't')
ON CONFLICT DO NOTHING;

-- Table: public.product_colors (5 rows)
INSERT INTO public."product_colors" ("id", "product_id", "color_id", "is_active") VALUES
  ('1a4ea90b-c5d2-4c72-ae0c-16f890455bd6', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '9b20bce5-c5f2-4b78-8d37-3a48822054f8', 't'),
  ('c20cd57f-3b15-412b-9064-600f4cb23bdb', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '107948df-b5a2-40b8-ad42-fe518caf5d31', 't'),
  ('950c8270-43d3-415f-9ebc-5fff63fa1923', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '67ce368a-6599-481a-a69c-6b79d4d00aa2', 'f'),
  ('a9d4be2c-967d-43bf-957e-672c9f6d208e', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '2281c271-71c6-4aa4-bbe3-855457fcc515', 'f'),
  ('6b96f4e4-bc0d-4bef-b3d2-4db608af551f', '36ffc468-746a-44dd-b7d9-9139356c9b5b', 'b9626bba-de79-48d5-bb92-b6cee94bf4ca', 'f')
ON CONFLICT DO NOTHING;

-- Table: public.product_images (36 rows)
INSERT INTO public."product_images" ("id", "product_id", "color_id", "image_url", "is_primary", "sort_order", "is_active") VALUES
  ('2ff7cfa1-6639-49d2-b59f-b84af2666da4', '2461b38e-3fb5-4dff-ba38-72206440328d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/1/1789232212690-ULTIMA6595.webp', 'f', '0', 't'),
  ('1fce072d-6f49-417f-8492-ee85d62d5dfd', '2461b38e-3fb5-4dff-ba38-72206440328d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/1/1789232213867-ULTIMA6590.webp', 'f', '1', 't'),
  ('4f3f581b-4330-47a7-8c70-052a3ac375e9', '2461b38e-3fb5-4dff-ba38-72206440328d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/1/1789232215208-ULTIMA6578.webp', 'f', '2', 't'),
  ('842c4d29-2b1a-411e-b3d8-c592ad1fa5d6', '2461b38e-3fb5-4dff-ba38-72206440328d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/1/1789232215926-ULTIMA6589.jpg', 'f', '3', 't'),
  ('5c048bcd-5a3e-4f7a-a000-348359240f07', '2461b38e-3fb5-4dff-ba38-72206440328d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/1/1789232216741-ULTIMA6588.webp', 'f', '4', 't'),
  ('f2655827-4b55-4cb7-8d79-b0062cfa4b53', '2461b38e-3fb5-4dff-ba38-72206440328d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/1/1789232217412-ULTIMA6582.webp', 't', '5', 't'),
  ('b39e0b4a-ba80-4e8f-9c96-9b8c866e721d', '2461b38e-3fb5-4dff-ba38-72206440328d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/1/1789232218356-51HmAs_VvvL._SX679_cedf5e68-2939-4483-994b-d141063c8ce9.webp', 'f', '6', 't'),
  ('475d0482-2901-412d-8e45-c6548b319fc7', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/2/1789234383016-VP-MI-TR-UNICL-10P-PO4_8.webp', 'f', '0', 't'),
  ('846f72ab-6191-464e-887f-6da0feec06d3', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/2/1789234384070-VP-MI-TR-UNICL-10P-PO3_5.webp', 't', '1', 't'),
  ('26a02837-0860-400f-a7db-faef7e82fd1c', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/2/1789234385067-VP-MI-TR-UNICL-10P-PO3_4.webp', 'f', '2', 't'),
  ('48555a6b-7d98-4e91-be43-fefe92f6d4f0', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/2/1789234386251-VP-MI-TR-UNICL-10P-PO3_8.webp', 'f', '3', 't'),
  ('142d920e-651e-43d3-aade-098a3525c069', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/2/1789234386880-VP-MI-TR-UNICL-10P-PO3_3.webp', 'f', '4', 't'),
  ('314ee97c-b775-44ad-ae65-0ec20b1da47c', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/2/1789234387359-VP-MI-TR-UNICL-10P-PO3_6.webp', 'f', '5', 't'),
  ('678e6529-8399-4bcc-af9f-25538a6487cc', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/2/1789234387873-VP-MI-TR-UNICL-10P-PO3_2.webp', 'f', '6', 't'),
  ('250bf48a-1a00-436a-b569-0b88fc12abf6', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/2/1789234388334-VP-MI-TR-UNICL-10P-PO3_7.webp', 'f', '7', 't'),
  ('2ddd022c-8b2b-4c78-8740-5013bc595be7', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/3/1789235545648-BRIEFFRENCHIEPLUSBLACKM_7.webp', 'f', '0', 't'),
  ('a11e8af3-79f9-4639-b77e-016a93cc8e8c', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/3/1789235552367-BRIEFFRENCHIEPLUSFORESTGREENM_1.webp', 'f', '1', 't'),
  ('c1d2164d-8b32-46ae-9dc2-83eb42882ebb', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/3/1789235553555-Plus_1_40.webp', 'f', '2', 't'),
  ('1222004c-cc7e-4d16-97b4-0476af935482', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/3/1789235555190-Plus_1_3.webp', 'f', '3', 't'),
  ('92e2b3c0-d3c4-4b93-97b6-39eb1e7a9f74', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/3/1789235556377-BRIEFFRENCHIEPLUSNAVYBLUEM_5.webp', 'f', '4', 't'),
  ('cf428a9f-85ef-4142-9017-49139e514f4e', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/3/1789235557854-Plus_1_45.webp', 'f', '5', 't'),
  ('d4386228-cedf-488b-af35-25f05251bb05', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/3/1789235558609-BRIEFFRENCHIEPLUSNAVYBLUEM_2.webp', 'f', '6', 't'),
  ('3aa6b490-af49-43da-9c80-3e6dc88bc79a', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/3/1789235559480-BRIEFFRENCHIEPLUSBLACKM_4.webp', 'f', '7', 't'),
  ('5392b4ff-2fdd-4d9a-ae07-20ebddc390d6', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/3/1789235560367-BRIEFFRENCHIEPLUSFORESTGREENM_3.webp', 'f', '8', 't'),
  ('83e03736-0df4-436e-b8f8-86044776c22f', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/3/1789235561492-BRIEFFRENCHIEPLUSBLACKM_1.webp', 't', '9', 't'),
  ('4a23792c-fe81-446c-a644-e2961fcb7e1b', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '107948df-b5a2-40b8-ad42-fe518caf5d31', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/4/1789286634599-VIP7842.webp', 't', '6', 't'),
  ('0493e7d2-e510-47ae-96ac-27b2995a2de7', '36ffc468-746a-44dd-b7d9-9139356c9b5b', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/4/1789236556338-VIP7546.webp', 'f', '0', 't'),
  ('b6cc1cab-b8f9-4285-9a98-e9f0556b943a', '36ffc468-746a-44dd-b7d9-9139356c9b5b', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/4/1789236557620-VIP7559.webp', 'f', '1', 't'),
  ('8ca87426-96dc-45aa-a744-58f18b7b7cdd', '36ffc468-746a-44dd-b7d9-9139356c9b5b', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/4/1789236558243-VIP7564.webp', 'f', '2', 't'),
  ('51d0b0f1-499d-43a8-864a-3f09618c0bc8', '36ffc468-746a-44dd-b7d9-9139356c9b5b', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/4/1789236558815-VIP7551.webp', 'f', '3', 't'),
  ('68ba193c-2759-4196-83ef-b41e3930b946', '36ffc468-746a-44dd-b7d9-9139356c9b5b', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/4/1789236560627-VIP7544.webp', 'f', '4', 't'),
  ('8b6be47b-9e78-4b46-9169-87ab3965df01', '36ffc468-746a-44dd-b7d9-9139356c9b5b', NULL, 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/4/1789236561203-VIP7569.webp', 'f', '5', 't'),
  ('6b15502b-91ff-4029-9187-0f02850f58f1', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '107948df-b5a2-40b8-ad42-fe518caf5d31', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/4/1789286637781-VIP7818.webp', 'f', '7', 't'),
  ('b01745bf-045a-49e6-b81f-8bdf98249663', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '107948df-b5a2-40b8-ad42-fe518caf5d31', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/4/1789286638369-VIP7830.webp', 'f', '8', 't'),
  ('72373a69-bf1f-41d1-9b0a-dcb35200eff3', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '107948df-b5a2-40b8-ad42-fe518caf5d31', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/4/1789286639041-VIP7827.webp', 'f', '9', 't'),
  ('a272dc67-9333-4638-9abb-0cfcecba682a', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '107948df-b5a2-40b8-ad42-fe518caf5d31', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/product-images/4/1789286639819-VIP7834.webp', 'f', '10', 't')
ON CONFLICT DO NOTHING;

-- Table: public.addresses (1 rows)
INSERT INTO public."addresses" ("id", "user_id", "label", "full_name", "phone", "line1", "line2", "city", "state", "pincode", "is_default", "created_at") VALUES
  ('7d469146-eb68-4fa8-a04e-f23fa08821db', '132f5f5b-74b2-456a-9f86-976df91c3809', 'Home', 'Kartik', '9484634082', '140/B Radha Krishna Soc.', 'Near akota garden', 'Vadodara', 'Gujarat', '390020', 't', '2026-09-13 09:29:39.445596+00')
ON CONFLICT DO NOTHING;

-- Table: public.carousels (2 rows)
INSERT INTO public."carousels" ("id", "title", "image_url", "brand_id", "sort_order", "is_active", "created_at", "updated_at") VALUES
  ('2d8c6695-6744-4cf4-a35b-d42aed0a7242', 'VIP Frenchie', 'https://vip.in/cdn/shop/files/Frenchie_a15cb961-d59b-4c01-8476-822ab1f8b359.jpg?v=1789027239&width=2200', 'c3f535eb-1ab9-4b6d-bf8d-49e0ba89b9db', '1', 't', '2026-09-12 16:32:09.788693+00', '2026-09-12 16:32:09.788693+00'),
  ('607352f8-6d11-46b0-9814-c321d342416a', 'Bumchum T-shirts', 'https://mioaooryvahjrmcxnrgy.supabase.co/storage/v1/object/public/carousel-images/1789230969473-Bumchums-Crew-Neck-t-Shirt-comfort.webp', 'ead39108-640a-4ad7-97c8-fbadbacc67d5', '2', 't', '2026-09-12 16:36:09.987929+00', '2026-09-12 16:36:27.843+00')
ON CONFLICT DO NOTHING;

-- Table: public.inventory (24 rows)
INSERT INTO public."inventory" ("id", "product_id", "product_size_id", "product_color_id", "quantity", "reserved_quantity", "reorder_level", "warehouse_location", "created_at", "updated_at") VALUES
  ('9445c5b8-3d39-47df-a473-dbc62e5334d3', '2461b38e-3fb5-4dff-ba38-72206440328d', '9b8c33ab-17d7-400c-bd81-fe5ab531f619', NULL, '5', '0', '2', NULL, '2026-09-12 16:56:52.448414+00', '2026-09-12 17:00:02.447+00'),
  ('316c194f-f168-466d-9190-f50633ccbb94', '2461b38e-3fb5-4dff-ba38-72206440328d', '3bfb7dd6-ca58-4e37-928b-687419461b58', NULL, '5', '0', '2', NULL, '2026-09-12 16:56:52.445494+00', '2026-09-12 17:00:05.148+00'),
  ('0342e52c-7b13-433e-a387-667aca4b4dc2', '2461b38e-3fb5-4dff-ba38-72206440328d', 'df51a9ca-b0e6-42d7-ad36-06063aba1380', NULL, '5', '0', '2', NULL, '2026-09-12 16:56:52.448937+00', '2026-09-12 17:00:13.888+00'),
  ('fd738f03-91c5-45de-89d0-46437bd29283', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', 'c1420e62-bdf0-4d52-8a50-4895dfc520e9', NULL, '5', '0', '2', NULL, '2026-09-12 17:33:02.722772+00', '2026-09-12 17:35:34.053+00'),
  ('c09a0c8e-f722-4703-aaa5-39ef6d643876', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', '568f1efe-b209-44ae-ab3e-4ee1de2f9152', NULL, '5', '0', '2', NULL, '2026-09-12 17:33:02.729844+00', '2026-09-12 17:35:36.446+00'),
  ('fa967a18-3bfd-4d49-ad0a-59b4d330d41d', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', '75119ada-8eaf-48ce-96ec-6f3952cb2e5f', NULL, '5', '0', '2', NULL, '2026-09-12 17:33:02.728159+00', '2026-09-12 17:35:38.46+00'),
  ('c25e0051-05f5-4520-bc5a-28c835cb3c45', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', 'e147ae5a-6a02-4857-9c44-1a049cb83797', NULL, '5', '0', '2', NULL, '2026-09-12 17:33:02.727167+00', '2026-09-12 17:35:40.113+00'),
  ('f08f25b5-ded8-471f-b498-f75d166250b8', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', '136f3a11-7382-481e-943b-559f44fdf863', NULL, '5', '0', '2', NULL, '2026-09-12 17:33:02.723107+00', '2026-09-12 17:35:42.407+00'),
  ('63db38d9-56cd-43da-aa43-41babd5b57c7', '3a9c9ee7-2910-49d2-853a-82f419c61ae6', '9d3de1f1-a9ba-4dbf-9d19-c806c1135c17', NULL, '5', '0', '2', NULL, '2026-09-12 17:33:02.722613+00', '2026-09-12 17:35:46.767+00'),
  ('d8970cda-0ae9-442e-ae39-6f5ec28a0f07', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', '5a490137-f048-4ed6-ba75-a68bf9e314ef', NULL, '5', '0', '0', NULL, '2026-09-12 17:52:25.280958+00', '2026-09-12 18:00:57.404+00'),
  ('c5efa055-77c7-4612-ae9a-307a78637afc', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', 'ab88fc21-a4b5-496a-bba7-b6e8266fad08', NULL, '5', '0', '0', NULL, '2026-09-12 17:52:25.282276+00', '2026-09-12 18:01:00.045+00'),
  ('e92c54c6-40e2-48f8-a2a2-4d69dd80994c', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', 'fe8d106f-32ff-4ffb-b077-90c0e4fd6f84', NULL, '5', '0', '0', NULL, '2026-09-12 17:52:25.28307+00', '2026-09-12 18:01:01.481+00'),
  ('f93ebc3b-c140-45d1-beea-e48e42fbebe9', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', '2b937abe-f06b-4ca7-bf8b-c6257eb5971f', NULL, '5', '0', '0', NULL, '2026-09-12 17:52:25.287067+00', '2026-09-12 18:01:02.92+00'),
  ('bcbac679-d75f-44a0-94db-b06afe4ace69', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', '46730c4f-90ad-4772-82e7-4851db99b5af', NULL, '5', '0', '0', NULL, '2026-09-12 17:52:25.288128+00', '2026-09-12 18:01:06.839+00'),
  ('864c3334-10ac-4497-be3c-6b34516145a3', 'a4056700-524f-4e88-bbe2-b2ba08db7e5d', '44b32192-256f-48c5-aa09-0ec9aa2c2cbc', NULL, '5', '0', '0', NULL, '2026-09-12 17:52:25.30097+00', '2026-09-12 18:01:09.357+00'),
  ('07a106ca-4461-460f-924d-ae037bc36718', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '87cd4dab-dabc-4802-a92e-ccbe3daa8bd3', '1a4ea90b-c5d2-4c72-ae0c-16f890455bd6', '0', '0', '10', NULL, '2026-09-13 07:38:14.117583+00', '2026-09-13 07:38:14.117583+00'),
  ('429f1402-0bd5-4655-98c1-8ea444074aa3', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '08954035-99fa-4258-b28d-67ff2c54969e', '1a4ea90b-c5d2-4c72-ae0c-16f890455bd6', '0', '0', '10', NULL, '2026-09-13 07:38:14.117583+00', '2026-09-13 07:38:14.117583+00'),
  ('afda3c51-9e95-466b-b75f-29da85b7c1bd', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '6b0d1136-3951-4898-b356-1ec8642a6176', '1a4ea90b-c5d2-4c72-ae0c-16f890455bd6', '0', '0', '10', NULL, '2026-09-13 07:38:14.117583+00', '2026-09-13 07:38:14.117583+00'),
  ('76532030-948c-449d-b54a-461e5c9d6634', '36ffc468-746a-44dd-b7d9-9139356c9b5b', 'cd1e67e4-e7f9-4fdc-af60-eb9798cfe04c', '1a4ea90b-c5d2-4c72-ae0c-16f890455bd6', '0', '0', '10', NULL, '2026-09-13 07:38:14.117583+00', '2026-09-13 07:38:14.117583+00'),
  ('6b9f288f-63b6-4e86-842b-668ad9f081ad', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '87cd4dab-dabc-4802-a92e-ccbe3daa8bd3', 'c20cd57f-3b15-412b-9064-600f4cb23bdb', '5', '0', '10', NULL, '2026-09-13 08:03:54.305072+00', '2026-09-13 08:03:54.305072+00'),
  ('bf6ad69a-8d6b-4970-b84c-408e3fa88aed', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '08954035-99fa-4258-b28d-67ff2c54969e', 'c20cd57f-3b15-412b-9064-600f4cb23bdb', '5', '0', '10', NULL, '2026-09-13 08:03:54.305072+00', '2026-09-13 08:03:54.305072+00'),
  ('191395b7-0e2a-4e26-8808-83ccb166c7a7', '36ffc468-746a-44dd-b7d9-9139356c9b5b', '6b0d1136-3951-4898-b356-1ec8642a6176', 'c20cd57f-3b15-412b-9064-600f4cb23bdb', '5', '0', '10', NULL, '2026-09-13 08:03:54.305072+00', '2026-09-13 08:03:54.305072+00'),
  ('a7fabac0-d30a-4d5f-824d-f5e86d19628d', '36ffc468-746a-44dd-b7d9-9139356c9b5b', 'cd1e67e4-e7f9-4fdc-af60-eb9798cfe04c', 'c20cd57f-3b15-412b-9064-600f4cb23bdb', '5', '0', '10', NULL, '2026-09-13 08:03:54.305072+00', '2026-09-13 08:03:54.305072+00'),
  ('aa7a4bee-27d0-419a-8d7b-3ac34cd6d009', '2461b38e-3fb5-4dff-ba38-72206440328d', '9a432c38-3771-44aa-bb6a-1c4b10aa34f2', NULL, '4', '0', '2', NULL, '2026-09-12 16:56:52.44485+00', '2026-09-13 09:30:42.411354+00')
ON CONFLICT DO NOTHING;

-- Table: public.orders (1 rows)
INSERT INTO public."orders" ("id", "user_id", "address_id", "coupon_id", "status", "payment_status", "payment_method", "payment_id", "subtotal", "discount_amount", "delivery_charge", "total_amount", "notes", "created_at", "updated_at") VALUES
  ('28c0a168-f7e6-4a3e-9902-d466611bf331', '132f5f5b-74b2-456a-9f86-976df91c3809', '7d469146-eb68-4fa8-a04e-f23fa08821db', NULL, 'processing', 'paid', 'razorpay', 'pay_TbTL0x1v9a3vZb', '165.00', '0.00', '99.00', '264.00', NULL, '2026-09-13 09:30:41.800595+00', '2026-09-13 09:30:41.800595+00')
ON CONFLICT DO NOTHING;

-- Table: public.order_items (1 rows)
INSERT INTO public."order_items" ("id", "order_id", "product_id", "product_size_id", "product_color_id", "quantity", "unit_price", "total_price") VALUES
  ('d4dad7d8-08b2-40e5-bbea-f4055d48a185', '28c0a168-f7e6-4a3e-9902-d466611bf331', '2461b38e-3fb5-4dff-ba38-72206440328d', '9a432c38-3771-44aa-bb6a-1c4b10aa34f2', NULL, '1', '165.00', '165.00')
ON CONFLICT DO NOTHING;

-- (no rows for public.reviews)

-- (no rows for public.cart)

-- (no rows for public.wishlist)

-- Table: public.notifications (1 rows)
INSERT INTO public."notifications" ("id", "user_id", "type", "title", "message", "entity_type", "entity_id", "is_read", "created_at", "read_at") VALUES
  ('63125edc-cc71-4ff1-900f-944bbb98e8ea', '132f5f5b-74b2-456a-9f86-976df91c3809', 'order_created', 'Order placed successfully', 'Your order #1 has been placed successfully.', 'order', '28c0a168-f7e6-4a3e-9902-d466611bf331', 't', '2026-09-13 09:30:42.711642+00', '2026-09-13 09:31:29.41+00')
ON CONFLICT DO NOTHING;

-- (no rows for public.videos)

-- Table: public.users (1 rows)
INSERT INTO public."users" ("id", "email", "full_name", "phone", "is_admin", "is_active", "created_at", "updated_at") VALUES
  ('132f5f5b-74b2-456a-9f86-976df91c3809', 'kartikgupta1805@gmail.com', '', NULL, 't', 't', '2026-09-12 11:16:03.434829+00', '2026-09-12 11:16:03.434829+00')
ON CONFLICT DO NOTHING;

COMMIT;
